### ISSUE TITLE
Need Set Fixed Height  and Width

### ISSUE THREAD

**Issue by Hatef-Rostamkhani** [bnewell/AutoCollage#1]
Hi dear.
Your code is awesome , 
I can not set height.
I need generate image auto collage based fix resolution width and height   like that picasa or https://www.photocollage.com/ and 
thank you so much.

**Comment by bnewell** [comment]
Hey, thanks for the compliment. Due to the nature of how the software
automates the collage, you can only specify a width or a height for the
collage, but not both. This is a necessary part of the code that allows
each of the images to retain their respective aspect ratio. Hope this helps.

Regards,
Ben

**Comment by Hatef-Rostamkhani** [comment]
Hi dear,
Totally your answer is true . 
but i need any code like your code can set fixed resolution.
if you can make new feature in this code. will this is very good and unique feature.
thank you so much.
